# IBM Guestbook image version ibmcom/guestbook:v1
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: tecbrix/guestbook
  tag: v1
  pullPolicy: Always

# For some dev env (like minikube), you may need to set the type to NodePort
service:
  type: ClusterIP
  port: 8000
  subnetID: dummy-network-id
  affinityMode: SOURCE_IP
  elbClass: union
  lbType: public
  bandwidthChargeMode: bandwidth
  bandwidthShareType: PER
  bandwidthSize: 5
  EIPType: 5_bgp

app:
  type: tcp
  port: 3000

redis:
  port: 6379
  slaveEnabled: false
