apiVersion: v1
kind: Service
metadata:
  name: {{ include "ecommdemo.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "ecommdemo.name" . }}
    helm.sh/chart: {{ include "ecommdemo.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    kubernetes.io/elb.subnet-id: {{ .Values.service.subnetID }}
    kubernetes.io/elb.class: union
    kubernetes.io/session-affinity-mode: SOURCE_IP
    kubernetes.io/elb.autocreate: '{"type":"{{ .Values.service.lbType }}","bandwidth_name":"cce-bandwidth-{{ include "ecommdemo.fullname" . }}","bandwidth_chargemode":"{{ .Values.service.bandwidthChargeMode }}","bandwidth_size":{{ .Values.service.bandwidthSize }},"bandwidth_sharetype":"{{ .Values.service.bandwidthShareType }}","eip_type":"{{ .Values.service.EIPType }}","name":"{{ .Release.Name }}"}'
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: http-server
  selector:
    app.kubernetes.io/name: {{ include "ecommdemo.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
